### ISSUE TITLE
Fill in license template

### ISSUE THREAD

**Issue by v1993** [Martchus/qtutilities#1]
Look at this lines:

https://github.com/Martchus/qtutilities/blob/390716a330b34ddd8a7d4e0609797ef6d64cf04a/LICENSE#L293-L294
You probably want to fill them with actual data.

**Comment by Martchus** [comment]
I would possibly want to attach this header (with actual data filled in) to the start of every source file but not fill the template within the LICENSE file itself.

**Comment by Martchus** [comment]
Closing as there's no response for over a year.
