### ISSUE TITLE
please consider prefixing under "martchus-" namespace

### ISSUE THREAD

**Issue by sten0** [Martchus/qtutilities#3]
Hi @Martchus,

Thank you for syncthingtray, and its dependencies.  I have been planning to package them for Debian for some time.  All derivatives such as Ubuntu will also benefit.  Would you please consider prefixing cpp-utilities under "martchus-" namespace?  eg: `marchus-qtutilities` rather than `qtutilities`.  Providing a mechanism to do this during built-time would also work.  The issue is that Debian has many packages, and names like `qtutilities` will eventually cause conflicts between packages.  No need to rename the project, of course!

Thank you for your consideration,
Nicholas

**Comment by Martchus** [comment]
I'm closing this because I have already responded on https://github.com/Martchus/cpp-utilities/issues/16 and it doesn't make sense to split the conversation into different issues.
