### ISSUE TITLE
a lot of includes are missing

### ISSUE THREAD

**Issue by TagoriaTar** [Martchus/qtutilities#4]
A lot if includes are missing:
#include <c++utilities/io/path.h>
#include <c++utilities/application/argumentparser.h>
#include <c++utilities/conversion/stringconversion.h>
#include <c++utilities/io/ansiescapecodes.h>
#include <c++utilities/application/global.h>
#include <c++utilities/application/argumentparser.h>

**Comment by Martchus** [comment]
I don't understand the issue description. What is the problem (compilation error, used commands to compile, …)? Note that this library depends on c++utilities. That means these header files are *not* missing and are expected to be provided by c++utilities. Please read the README.

**Comment by Martchus** [comment]
Closing as there's no response for over a year.
